version: '2'
services:
  r:
    image: nathandemaria/qwop_slaver
    ports:
    - "8787:8787"
    depends_on:
    - selenium
  selenium:
    image: selenium/standalone-firefox-debug
    ports:
    - "4444:4444"
